Feat/goh 8/secure backend
GoHappy-Club/Go-Happy-Backend pull request #18
Opened 2024-07-18 17:38 UTC by mehul-gohappy

2024-07-20 03:49 UTC, Rakshit1411 requested changes

2024-07-20 03:49 UTC, Rakshit1411 commented on src/main/java/com/startup/goHappy/SecurityConfig.java
> +                .anyRequest().hasAnyRole("ADMIN", "USER")
What does this mean ?

2024-07-20 03:49 UTC, Rakshit1411 commented on src/main/java/com/startup/goHappy/SecurityConfig.java
> +                .anyRequest().hasAnyRole("ADMIN", "USER")
line 54

2024-07-20 04:25 UTC, mehul-gohappy commented on src/main/java/com/startup/goHappy/SecurityConfig.java
> +                .anyRequest().hasAnyRole("ADMIN", "USER")
Any route except the above routes will be accessible to user with role "USER" (for our app, that will be accessing all the other routes)

2024-07-20 11:49 UTC, Rakshit1411 approved these changes

2024-09-04 12:25 UTC, Rakshit1411 approved these changes

2024-09-04 12:25 UTC, merged