add one more field for whatsappHelpLink
GoHappy-Club/Go-Happy-Backend pull request #32
Opened 2024-09-16 08:11 UTC by mehul-gohappy

2024-09-17 01:14 UTC, Rakshit1411 requested changes

2024-09-17 01:14 UTC, Rakshit1411 commented on src/main/java/com/startup/goHappy/entities/model/Properties.java
> +    private String whatsappHelpLink;
bhai purane wale ko toh vapis list se string krdo fir

2024-09-17 02:03 UTC, mehul-gohappy commented on src/main/java/com/startup/goHappy/entities/model/Properties.java
> +    private String whatsappHelpLink;
No, usme whatsapp groups hai, and isme whatsapp help wala, jo hum overview screen pr Get Help pr hai

2024-09-19 01:44 UTC, Rakshit1411 approved these changes

2024-09-19 01:44 UTC, merged